### ISSUE TITLE
[Bug] Incorrect YAML syntax

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_twilio#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

`test` instead of `tests` at:
- https://github.com/fivetran/dbt_twilio/blob/26ca6ca19baa602b551147778099b7e9e6b9d9bb/models/twilio.yml#L51
- https://github.com/fivetran/dbt_twilio/blob/26ca6ca19baa602b551147778099b7e9e6b9d9bb/models/twilio.yml#L117

### Expected behavior

N/A

### dbt Project configurations

N/A

### Package versions

N/A

### What database are you using dbt with?

snowflake

### dbt Version

N/A

### Additional Context

FYI @fivetran-reneeli 

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-jamie** [comment]
hey @raphaelvarieras great catch, this is certainly something we wanna fix. On your end, is this causing any failure, or are the relevant models just not being tested by `dbt test`? 

If you're still open to contributing the fix for this, this would speed things up as we would prioritize reviewing any PR asap. If not, we will slate this into an upcoming sprint to work on

**Comment by raphaelvarieras** [comment]
Ok, I'll prepare a PR some time soon.

**Comment by raphaelvarieras** [comment]
@fivetran-jamie ready for your 👀 !

**Comment by fivetran-jamie** [comment]
in v0.2.0 which is now live!
